### ISSUE TITLE
Fix RTL pages

### ISSUE THREAD

**Issue by TheoChevalier** [mozilla/mrburns#144]
I'm working on it, should be ready for Monday

**Comment by bensternthal** [comment]
That would be a fantastic help. Make sure you take the bug in bugzilla so that no one else is working on it at the same time.
I'll be online sunday if you need help with anything.

**Comment by TheoChevalier** [comment]
Fixed by Kohei in https://github.com/mozilla/mrburns/pull/153

**Comment by kyoshino** [comment]
Sorry I didn't notice this issue!
