### ISSUE TITLE
Privacy and legal links not clickable in all viewport sizes

### ISSUE THREAD

**Issue by chrismore** [mozilla/mrburns#167]
When the viewport size is larger than 1086 pixels wide, the privacy and legal links are not clickable. Try it for yourself with the responsive design view tool in Firefox.

**Comment by chrismore** [comment]
@kyoshino does this happen for you too?

**Comment by chrismore** [comment]
@sgarrity ^^

**Comment by jgmize** [comment]
This is happening to me on Aurora and Release.

**Comment by kyoshino** [comment]
I can also reproduce the issue. Sent #168 to fix it.
