### ISSUE TITLE
Stale peep.py version

### ISSUE THREAD

**Issue by SamPenrose** [mozilla/mrburns#191]
I'm hitting this issue:
  https://github.com/erikrose/peep/issues/65
I have tried upgrading to the latest peep.py (2.4.1) and I get a conflict with the constructor of pip's PackageFinder:
  TypeError: **init**() got an unexpected keyword argument 'use_wheel'
I also tried monkeypatching in the specific fixes from 2.1, but pip has moved on. I'm going to see if I can get peep 2.4.1 working, but this is my first pip/peep exploration and advice would be most welcome.

**Comment by SamPenrose** [comment]
Removing 'use_wheel' made it work. I'll open an issue with peep to see how to proceed. Meanwhile, I got the following complaints from peep about the requirements:

THE FOLLOWING PACKAGES DIDN'T MATCH THE HASHES SPECIFIED IN THE REQUIREMENTS
FILE. If you have updated the package versions, update the hashes. If not,
freak out, because someone has tampered with the packages.

```
django-appconf: expected Ttop2OsMi0qDZmC17_eKDT4NxsGR6ZihQZTy_1ETDaM
                     got BrZLrybHpDbLuBRk56UAR66jDbEFnb5uCdxEPvojuiA
six: expected qI7Y-5I6U8cMLEb75FCLX4Fka0sBQB8VaKghZxszIVw
          got jzT1uJ4X-opuOUUxAxjL1cjLsW-iiPeOqW28cDRMsb8
django-extensions: expected one of qI7Y-5I6U8cMLEb75FCLX4Fka0sBQB8VaKghZxszIVw
                                   53T3tTehlADKaH9I01KrdGFzKsQThd2I_a1Hie-tKcU
                               got Xq3Xc16Qo9r3fzPFVMWo4pMCdDKQIWk2QedPlXqvnfw
django-redis: expected Zv8ahFpsGxbEz1Uu49dGAzl55GzZvV2ZnUtdrpMyelI
                   got 1atp0q0_RjLiD7c6rY0p7t2hfqDGgsQ9JaVkyKzoFE8
pathlib: expected r5dH7CcnQlsbCSUpdeIVAu5aPY0jXH9Jhp6xPgnM9OQ
              got MGMUs3hvTFNNDPYYyw08qPHxamnbOZ0hwFcc4mYeIPY
polib: expected 1DkqfI2RsAXAAlaKhfr2F8ZyQcjNg5nMOV6PEAWv-A0
            got izJ291zi_OlELifbOuY9hCQW4X8OIJXzn_UtxzXldJo
```

The following packages had no hashes specified in the requirements file, which
leaves them open to tampering. Vet these packages to your satisfaction, then
add these "sha256" lines like so:

# sha256: Ttop2OsMi0qDZmC17_eKDT4NxsGR6ZihQZTy_1ETDaM

Django==1.6.5

# sha256: Zv8ahFpsGxbEz1Uu49dGAzl55GzZvV2ZnUtdrpMyelI

django-compressor==1.3

# sha256: wbr3o-i-cPNNkx7hcyg_QGh3vT0X83K76CMYpbPFEMw

Werkzeug==0.9.4

# sha256: tb0uG3jSgFEQjrqmJIdQIh-czvUrTwVMtyfeYbBAbeA

requests==2.2.1

# sha256: hSc7h6s9uTB-OxRSsHHiXB2xzIErwzfSqX6gsM8qtro

nose==1.3.1

# sha256: mq4WtWKGak3apeiXhymrrbvtVEco2I4LnJr3sx3Qcu0

django-nose==1.2

# sha256: Cmfp2wZbsEY3Xs9TS4l1JR3K86EHUgtFWZ6UmatYZlg

dennis==0.3.11

# sha256: L29VCf4YCuMJL9xVlYWoOjz84wr7qd4lzO_F7Pv-2_w

blessings==1.5.1

**Comment by SamPenrose** [comment]
This appears to be a sorting issue of some, er, sort. peep is in effect complaining that packages have each other's sha's.

**Comment by mythmon** [comment]
Something to note: No version of peep is compatible with Pip 7.x. The `TypeError: init() got an unexpected keyword argument 'use_wheel'` error you got is related to that. Downgrading to pip 6.x would fix that particular issue.

The hash mismatches are likely due to Pip 7 defaulting to using wheels, and the hashes you have written down are likely for not-wheels. I predict that using Pip 6 and passing `--no-use-wheel` will fix your problem.

**Comment by SamPenrose** [comment]
@erikrose helpfully informed me via that:
- peep is not and may never been pip 7 compatible
- the underlying issue will likely be fixed with pip 8, due next year
  Options include:
  1) requiring pip 6
  2) monkey-patching peep to disable it
  3) adopting one of the peep pip-7-compatible PRs, which Erik does not currently intend to merge
  4) redoing the installation to not run through peep

**Comment by pmclanahan** [comment]
Are you trying to install and use mrburns for something? This project is basically abandoned and the [site running it](https://webwewant.mozilla.org) is in archive mode showing archived data.

**Comment by erikrose** [comment]
"The underlying issue" is kind of a funny way of saying it. Basically, pip 8 is gaining peep's functionality.

**Comment by SamPenrose** [comment]
Ali suggested trying mrburns to serve as the basis of a visualization of Firefox activity around the world that we'd like to do, which led to my discovering this issue. It sounds like if I want to use this code I should create a new project rather than send PRs to this one. I am not blocked. Thanks everyone for your time and thoughts.

**Comment by pmclanahan** [comment]
Ah! Makes sense now :) I think that this one shouldn't change, but please feel free to fork it or start fresh and copy stuff from it into your own thing.
