### ISSUE TITLE
Localized versions give a 500 error

### ISSUE THREAD

**Issue by pascalchevrel** [mozilla/mrburns#26]
UnicodeEncodeError at /de/
'ascii' codec can't encode character u'\xdf' in position 6: ordinal not in range(128)

I tried to find the problem and it seems that it lies in get_tw_share_url(), if you make it return False or an empty string, the site displays normally. I believe it may be the urlencode() function that doesn't handle unicode strings, it doesn't happen for en-US because strings are in ascii:

```
        'share_map_twitter': get_tw_share_url({
            'url': 'https://webwewant.mozilla.org/#web',
            'hashtags': '#firefox',
            'dnt': True,
            'text': _('Join millions of Firefox users around the world '
                      'who are shaping the future of the Web.'),
        }),
```

**Comment by pmclanahan** [comment]
Fixed in 5544abeccf85a78da0fce09109e89ad71c9b4b68
