### ISSUE TITLE
String extracted by Django with a double %

### ISSUE THREAD

**Issue by pascalchevrel** [mozilla/mrburns#27]
One string is displaying in English because the string in to po file differs from the one in the templates:

"Firefox is the only browser made of 100%% free, open source code that anyone can view, remix and contribute to."

While the templates use 100% with a single percent.

I don't know if it is a bug Django gettext support of if the string was wrong when if was extracted and later fixed.

**Comment by pmclanahan** [comment]
This still an issue? It should have extracted with the double %%, but didn't initially due to not using the `{% trans ... %}` tag. I fixed that and I thought fixed the string IDs. I believe all that's needed is to fix the string IDs if it's still not working.

**Comment by pmclanahan** [comment]
I believe this is fixed. Please reopen if it is not. Thanks Pascal!
