### ISSUE TITLE
High-level JS review

### ISSUE THREAD

**Issue by alexgibson** [mozilla/mrburns#73]
As requested by @sgarrity, I've taken a look over the JS at a high level and made some notes for review. I figured I would open an issue here as probably the best way to keep track as it makes discussion / notes easier.

Main things to clean up:
- There are a lot of global variables and functions that probably don't need to be. Also 'use strict' is set in global scope, so if things are concatenated in production this could be applied to external libs also? Suggest wrapping each JS file in a jQuery ready handler. If you need a global var or function or two, I suggest using a namespace like `Mozilla.Glow.foo` (or something).
- There are a fair few jQuery selectors that can probably benefit from caching when the page loads to avoid querying the DOM multiple times, e.g: https://github.com/mozilla/mrburns/blob/master/mrburns/main/static/js/stats.js#L51-58
- quite a few `console.log` messages scattered throughout the JS that need removing.

Minor query's / suggestions:
- Include Mozilla Public License at top of individual files.
- could you use `$.parseJSON` instead of `eval`? https://github.com/mozilla/mrburns/blob/master/mrburns/main/static/js/stats.js#L112
- could use a `setInterval` here that clears after 60 seconds instead of repeating timeouts and duplicating code? https://github.com/mozilla/mrburns/blob/master/mrburns/main/static/js/map.js#L321-353

Nit picky coding style stuff:

Mostly stuff from http://mozweb.readthedocs.org/en/latest/js-style.html

(Feel free to ignore nit picky stuff unless there's time to spare)
- There's a mixture of underscore and camel case variable naming. Suggest sticking to camelCase as it's more consistent with native conventions & third parts libs.
- JS variables should be assigned on a newline, not comma separated.
- Use single quotes in JS/jQuery selectors for consistency. We only really use double quotes for html attributes.

Over all things look good, nice work! I took a scan through the less files and templates and things look good.

P.S - I like the use of `π` as a valid JS variable name. Looks like there's some fun to be had there: http://mathiasbynens.be/notes/javascript-identifiers

**Comment by pmclanahan** [comment]
Nice! Thanks a lot @alexgibson !

**Comment by almossawi** [comment]
Thank you, @alexgibson.

**Comment by pmclanahan** [comment]
Thanks again Alex.
